version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_User: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  example_db: